export const Calendar = () => {
    return (
        <table>
            <thead>
                <tr>
                    <th>Lunes</th>
                    <th>Martes</th>
                    <th>Miercoles</th>
                    <th>Jueves</th>
                    <th>Viernes</th>
                    <th>Sábado</th>
                    <th>Domingo</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Gim</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Gim</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Caminar</td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    )
}